'use strict';

/**
 * AI 助手插件权限定义
 * code 命名规范：ai<Domain>.<action>
 */
module.exports = [
  // 模型管理
  {
    code: 'aiModel.list',
    method: 'GET',
    path: '/manage/ai/models',
    desc: '获取 AI 模型列表',
    group: 'ai-model',
    aliases: ['ai/models'],
  },
  {
    code: 'aiModel.detail',
    method: 'GET',
    path: '/manage/ai/models/:id',
    desc: '查看 AI 模型详情',
    group: 'ai-model',
    aliases: ['ai/models/detail'],
  },
  {
    code: 'aiModel.create',
    method: 'POST',
    path: '/manage/ai/models',
    desc: '创建 AI 模型',
    group: 'ai-model',
    aliases: ['ai/models/create'],
  },
  {
    code: 'aiModel.update',
    method: 'PUT',
    path: '/manage/ai/models/:id',
    desc: '更新 AI 模型',
    group: 'ai-model',
    aliases: ['ai/models/update'],
  },
  {
    code: 'aiModel.delete',
    method: 'DELETE',
    path: '/manage/ai/models/:id',
    desc: '删除 AI 模型',
    group: 'ai-model',
    aliases: ['ai/models/delete'],
  },
  {
    code: 'aiModel.toggle',
    method: 'PUT',
    path: '/manage/ai/models/:id/toggle',
    desc: '启用/禁用 AI 模型',
    group: 'ai-model',
    aliases: ['ai/models/toggle'],
  },
  {
    code: 'aiModel.stats',
    method: 'GET',
    path: '/manage/ai/models/:id/stats',
    desc: '查看 AI 模型统计',
    group: 'ai-model',
    aliases: ['ai/models/stats'],
  },
  {
    code: 'aiModel.batchDelete',
    method: 'DELETE',
    path: '/manage/ai/models/batch',
    desc: '批量删除 AI 模型',
    group: 'ai-model',
    aliases: ['ai/models/batchDelete'],
  },
  {
    code: 'aiProvider.list',
    method: 'GET',
    path: '/manage/ai/providers',
    desc: '获取 AI 提供商列表',
    group: 'ai-model',
    aliases: ['ai/providers'],
  },
  {
    code: 'aiModel.testApiKey',
    method: 'POST',
    path: '/manage/ai/test-api-key',
    desc: '测试 AI API Key',
    group: 'ai-model',
    aliases: ['ai/testApiKey'],
  },

  // 内容生成
  {
    code: 'aiContent.generateTitle',
    method: 'POST',
    path: '/manage/ai/content/generate-title',
    desc: '生成文章标题',
    group: 'ai-content',
    aliases: ['ai/content/generateTitle'],
  },
  {
    code: 'aiContent.generateSummary',
    method: 'POST',
    path: '/manage/ai/content/generate-summary',
    desc: '生成文章摘要',
    group: 'ai-content',
    aliases: ['ai/content/generateSummary'],
  },
  {
    code: 'aiContent.extractTags',
    method: 'POST',
    path: '/manage/ai/content/extract-tags',
    desc: '提取文章标签',
    group: 'ai-content',
    aliases: ['ai/content/extractTags'],
  },
  {
    code: 'aiContent.extractKeywords',
    method: 'POST',
    path: '/manage/ai/content/extract-keywords',
    desc: '提取文章关键词',
    group: 'ai-content',
    aliases: ['ai/content/extractKeywords'],
  },
  {
    code: 'aiContent.matchCategory',
    method: 'POST',
    path: '/manage/ai/content/match-category',
    desc: '匹配文章分类',
    group: 'ai-content',
    aliases: ['ai/content/matchCategory'],
  },
  {
    code: 'aiContent.optimizeSEO',
    method: 'POST',
    path: '/manage/ai/content/optimize-seo',
    desc: '内容 SEO 优化',
    group: 'ai-content',
    aliases: ['ai/content/optimizeSeo'],
  },
  {
    code: 'aiContent.checkQuality',
    method: 'POST',
    path: '/manage/ai/content/check-quality',
    desc: '检查内容质量',
    group: 'ai-content',
    aliases: ['ai/content/checkQuality'],
  },
  {
    code: 'aiContent.generateBatch',
    method: 'POST',
    path: '/manage/ai/content/generate-batch',
    desc: '批量生成内容',
    group: 'ai-content',
    aliases: ['ai/content/generateBatch'],
  },
  {
    code: 'aiContent.clearCache',
    method: 'DELETE',
    path: '/manage/ai/content/cache',
    desc: '清除 AI 内容缓存',
    group: 'ai-content',
    aliases: ['ai/content/clearCache'],
  },
  {
    code: 'aiContent.cacheStats',
    method: 'GET',
    path: '/manage/ai/content/cache/stats',
    desc: '获取 AI 内容缓存统计',
    group: 'ai-content',
    aliases: ['ai/content/cacheStats'],
  },

  // 内容发布
  {
    code: 'aiPublish.publish',
    method: 'POST',
    path: '/manage/ai/content/publish',
    desc: 'AI 辅助发布内容',
    group: 'ai-publish',
    aliases: ['ai/content/publish'],
  },
  {
    code: 'aiPublish.batchPublish',
    method: 'POST',
    path: '/manage/ai/content/batch-publish',
    desc: '批量 AI 发布内容',
    group: 'ai-publish',
    aliases: ['ai/content/batchPublish'],
  },
  {
    code: 'aiPublish.previewEnhancements',
    method: 'POST',
    path: '/manage/ai/content/preview',
    desc: '预览 AI 增强效果',
    group: 'ai-publish',
    aliases: ['ai/content/preview'],
  },
  {
    code: 'aiPublish.publishModes',
    method: 'GET',
    path: '/manage/ai/content/publish-modes',
    desc: '获取 AI 发布模式',
    group: 'ai-publish',
    aliases: ['ai/content/publishModes'],
  },
  {
    code: 'aiPublish.enhancementOptions',
    method: 'GET',
    path: '/manage/ai/content/enhancement-options',
    desc: '获取 AI 增强选项',
    group: 'ai-publish',
    aliases: ['ai/content/enhancementOptions'],
  },

  // 图片生成
  {
    code: 'aiImage.generate',
    method: 'POST',
    path: '/manage/ai/image/generate',
    desc: '生成 AI 图片',
    group: 'ai-image',
    aliases: ['ai/image/generate'],
  },
  {
    code: 'aiImage.optimizePrompt',
    method: 'POST',
    path: '/manage/ai/image/optimize-prompt',
    desc: '优化图片提示词',
    group: 'ai-image',
    aliases: ['ai/image/optimizePrompt'],
  },
  {
    code: 'aiImage.batchGenerate',
    method: 'POST',
    path: '/manage/ai/image/batch-generate',
    desc: '批量生成图片',
    group: 'ai-image',
    aliases: ['ai/image/batchGenerate'],
  },
  {
    code: 'aiImage.models',
    method: 'GET',
    path: '/manage/ai/image/models',
    desc: '获取图片模型列表',
    group: 'ai-image',
    aliases: ['ai/image/models'],
  },
  {
    code: 'aiImage.sizes',
    method: 'GET',
    path: '/manage/ai/image/sizes/:modelId',
    desc: '获取模型支持尺寸',
    group: 'ai-image',
    aliases: ['ai/image/sizes'],
  },
  {
    code: 'aiImage.capabilities',
    method: 'GET',
    path: '/manage/ai/image/capabilities',
    desc: '获取图片生成能力说明',
    group: 'ai-image',
    aliases: ['ai/image/capabilities'],
  },
  {
    code: 'aiImage.examples',
    method: 'GET',
    path: '/manage/ai/image/examples',
    desc: '获取图片生成示例',
    group: 'ai-image',
    aliases: ['ai/image/examples'],
  },
];
