export const MAILDELIVERY_FORMSTATE = 'MAILDELIVERY_FORMSTATE';
export const MAILDELIVERY_LIST = 'MAILDELIVERY_LIST';
export const MAILTEMPLATE_LIST = 'MAILTEMPLATE_LIST';
export const MAIL_SENDLOG_FORMSTATE = 'MAIL_SENDLOG_FORMSTATE';
export const MAIL_SENDLOG_LIST = 'MAIL_SENDLOG_LIST';
