'use strict';

/**
 * ⚠️ 此文件由 scripts/generate-permissions.js 自动生成
 * 更新时间: 2025-11-13T01:38:53.136Z
 */

module.exports = [
  {
    code: 'menu.list',
    method: 'GET',
    path: '/manage/menu/getList',
    desc: '查询菜单列表',
    group: 'menu',
    aliases: ['menu/getList'],
  },
  {
    code: 'menu.create',
    method: 'POST',
    path: '/manage/menu/addOne',
    desc: '新增菜单',
    group: 'menu',
    aliases: ['menu/addOne'],
  },
  {
    code: 'menu.update',
    method: 'POST',
    path: '/manage/menu/updateOne',
    desc: '更新菜单',
    group: 'menu',
    aliases: ['menu/updateOne'],
  },
  {
    code: 'menu.delete',
    method: 'POST',
    path: '/manage/menu/deleteMenu',
    desc: '删除菜单',
    group: 'menu',
    aliases: ['menu/deleteMenu'],
  },
  {
    code: 'role.list',
    method: 'GET',
    path: '/manage/role/getList',
    desc: '查询角色列表',
    group: 'role',
    aliases: ['role/getList'],
  },
  {
    code: 'role.create',
    method: 'POST',
    path: '/manage/role/addOne',
    desc: '新增角色',
    group: 'role',
    aliases: ['role/addOne'],
  },
  {
    code: 'role.update',
    method: 'POST',
    path: '/manage/role/updateOne',
    desc: '更新角色',
    group: 'role',
    aliases: ['role/updateOne'],
  },
  {
    code: 'role.delete',
    method: 'POST',
    path: '/manage/role/deleteRole',
    desc: '删除角色',
    group: 'role',
    aliases: ['role/deleteRole'],
  },
  {
    code: 'admin.list',
    method: 'GET',
    path: '/manage/admin/getList',
    desc: '查询管理员列表',
    group: 'admin',
    aliases: ['admin/getList'],
  },
  {
    code: 'admin.create',
    method: 'POST',
    path: '/manage/admin/addOne',
    desc: '新增管理员',
    group: 'admin',
    aliases: ['admin/addOne'],
  },
  {
    code: 'admin.update',
    method: 'POST',
    path: '/manage/admin/updateOne',
    desc: '更新管理员',
    group: 'admin',
    aliases: ['admin/updateOne'],
  },
  {
    code: 'admin.delete',
    method: 'POST',
    path: '/manage/admin/deleteUser',
    desc: '删除管理员',
    group: 'admin',
    aliases: ['admin/deleteUser'],
  },
  {
    code: 'systemConfig.getConfig',
    method: 'GET',
    path: '/manage/systemConfig/getConfig',
    desc: '[AUTO] GET /manage/systemConfig/getConfig',
    group: 'systemConfig',
    aliases: ['systemConfig/getConfig'],
  },
  {
    code: 'systemConfig.addOne',
    method: 'POST',
    path: '/manage/systemConfig/addOne',
    desc: '[AUTO] POST /manage/systemConfig/addOne',
    group: 'systemConfig',
    aliases: ['systemConfig/addOne'],
  },
  {
    code: 'systemConfig.updateConfig',
    method: 'POST',
    path: '/manage/systemConfig/updateConfig',
    desc: '[AUTO] POST /manage/systemConfig/updateConfig',
    group: 'systemConfig',
    aliases: ['systemConfig/updateConfig'],
  },
  {
    code: 'systemConfig.deleteConfig',
    method: 'POST',
    path: '/manage/systemConfig/deleteConfig',
    desc: '[AUTO] POST /manage/systemConfig/deleteConfig',
    group: 'systemConfig',
    aliases: ['systemConfig/deleteConfig'],
  },
  {
    code: 'template.getList',
    method: 'GET',
    path: '/manage/template/getList',
    desc: '[AUTO] GET /manage/template/getList',
    group: 'template',
    aliases: ['template/getList'],
  },
  {
    code: 'template.getOne',
    method: 'GET',
    path: '/manage/template/getOne/:id',
    desc: '[AUTO] GET /manage/template/getOne/:id',
    group: 'template',
    aliases: ['template/getOne'],
  },
  {
    code: 'template.addOne',
    method: 'POST',
    path: '/manage/template/addOne',
    desc: '[AUTO] POST /manage/template/addOne',
    group: 'template',
    aliases: ['template/addOne'],
  },
  {
    code: 'template.updateOne',
    method: 'POST',
    path: '/manage/template/updateOne/:id',
    desc: '[AUTO] POST /manage/template/updateOne/:id',
    group: 'template',
    aliases: ['template/updateOne'],
  },
  {
    code: 'template.deleteOne',
    method: 'POST',
    path: '/manage/template/deleteOne',
    desc: '[AUTO] POST /manage/template/deleteOne',
    group: 'template',
    aliases: ['template/deleteOne'],
  },
  {
    code: 'template.deleteMany',
    method: 'POST',
    path: '/manage/template/deleteMany',
    desc: '[AUTO] POST /manage/template/deleteMany',
    group: 'template',
    aliases: ['template/deleteMany'],
  },
  {
    code: 'template.activate',
    method: 'POST',
    path: '/manage/template/activate/:id',
    desc: '[AUTO] POST /manage/template/activate/:id',
    group: 'template',
    aliases: ['template/activate'],
  },
  {
    code: 'template.deactivate',
    method: 'POST',
    path: '/manage/template/deactivate/:id',
    desc: '[AUTO] POST /manage/template/deactivate/:id',
    group: 'template',
    aliases: ['template/deactivate'],
  },
  {
    code: 'template.getActiveTheme',
    method: 'GET',
    path: '/manage/template/getActiveTheme',
    desc: '[AUTO] GET /manage/template/getActiveTheme',
    group: 'template',
    aliases: ['template/getActiveTheme'],
  },
  {
    code: 'template.installFromRemote',
    method: 'POST',
    path: '/manage/template/installFromRemote',
    desc: '[AUTO] POST /manage/template/installFromRemote',
    group: 'template',
    aliases: ['template/installFromRemote'],
  },
  {
    code: 'template.install',
    method: 'POST',
    path: '/manage/template/install',
    desc: '[AUTO] POST /manage/template/install',
    group: 'template',
    aliases: ['template/install'],
  },
  {
    code: 'template.uninstall',
    method: 'POST',
    path: '/manage/template/uninstall/:id',
    desc: '[AUTO] POST /manage/template/uninstall/:id',
    group: 'template',
    aliases: ['template/uninstall'],
  },
  {
    code: 'template.export',
    method: 'GET',
    path: '/manage/template/export/:id',
    desc: '[AUTO] GET /manage/template/export/:id',
    group: 'template',
    aliases: ['template/export'],
  },
  {
    code: 'template.checkIntegrity',
    method: 'GET',
    path: '/manage/template/checkIntegrity/:id',
    desc: '[AUTO] GET /manage/template/checkIntegrity/:id',
    group: 'template',
    aliases: ['template/checkIntegrity'],
  },
  {
    code: 'template.getTemplates',
    method: 'GET',
    path: '/manage/template/getTemplates/:id',
    desc: '[AUTO] GET /manage/template/getTemplates/:id',
    group: 'template',
    aliases: ['template/getTemplates'],
  },
  {
    code: 'template.updateStats',
    method: 'POST',
    path: '/manage/template/updateStats/:id',
    desc: '[AUTO] POST /manage/template/updateStats/:id',
    group: 'template',
    aliases: ['template/updateStats'],
  },
  {
    code: 'template.batchUpdateStatus',
    method: 'POST',
    path: '/manage/template/batchUpdateStatus',
    desc: '[AUTO] POST /manage/template/batchUpdateStatus',
    group: 'template',
    aliases: ['template/batchUpdateStatus'],
  },
  {
    code: 'template.getStats',
    method: 'GET',
    path: '/manage/template/getStats',
    desc: '[AUTO] GET /manage/template/getStats',
    group: 'template',
    aliases: ['template/getStats'],
  },
  {
    code: 'template.getTempsFromShop',
    method: 'GET',
    path: '/manage/template/getTempsFromShop',
    desc: '[AUTO] GET /manage/template/getTempsFromShop',
    group: 'template',
    aliases: ['template/getTempsFromShop'],
  },
  {
    code: 'template.preview',
    method: 'GET',
    path: '/manage/template/preview/:id',
    desc: '[AUTO] GET /manage/template/preview/:id',
    group: 'template',
    aliases: ['template/preview'],
  },
  {
    code: 'template.generateLayouts',
    method: 'POST',
    path: '/manage/template/generateLayouts/:id',
    desc: '[AUTO] POST /manage/template/generateLayouts/:id',
    group: 'template',
    aliases: ['template/generateLayouts'],
  },
  {
    code: 'template.batchGenerate',
    method: 'POST',
    path: '/manage/template/batchGenerate/:id',
    desc: '[AUTO] POST /manage/template/batchGenerate/:id',
    group: 'template',
    aliases: ['template/batchGenerate'],
  },
  {
    code: 'template.checkMissingTemplates',
    method: 'POST',
    path: '/manage/template/checkMissingTemplates/:id',
    desc: '[AUTO] POST /manage/template/checkMissingTemplates/:id',
    group: 'template',
    aliases: ['template/checkMissingTemplates'],
  },
  {
    code: 'template.getGenerationStatus',
    method: 'GET',
    path: '/manage/template/getGenerationStatus/:id',
    desc: '[AUTO] GET /manage/template/getGenerationStatus/:id',
    group: 'template',
    aliases: ['template/getGenerationStatus'],
  },
  {
    code: 'plugin.getList',
    method: 'GET',
    path: '/manage/plugin/getList',
    desc: '[AUTO] GET /manage/plugin/getList',
    group: 'plugin',
    aliases: ['plugin/getList'],
  },
  {
    code: 'plugin.installPlugin',
    method: 'GET',
    path: '/manage/plugin/installPlugin',
    desc: '[AUTO] GET /manage/plugin/installPlugin',
    group: 'plugin',
    aliases: ['plugin/installPlugin'],
  },
  {
    code: 'plugin.unInstallPlugin',
    method: 'GET',
    path: '/manage/plugin/unInstallPlugin',
    desc: '[AUTO] GET /manage/plugin/unInstallPlugin',
    group: 'plugin',
    aliases: ['plugin/unInstallPlugin'],
  },
  {
    code: 'plugin.updatePlugin',
    method: 'GET',
    path: '/manage/plugin/updatePlugin',
    desc: '[AUTO] GET /manage/plugin/updatePlugin',
    group: 'plugin',
    aliases: ['plugin/updatePlugin'],
  },
  {
    code: 'plugin.enablePlugin',
    method: 'POST',
    path: '/manage/plugin/enablePlugin',
    desc: '[AUTO] POST /manage/plugin/enablePlugin',
    group: 'plugin',
    aliases: ['plugin/enablePlugin'],
  },
  {
    code: 'plugin.pluginHeartBeat',
    method: 'GET',
    path: '/manage/plugin/pluginHeartBeat',
    desc: '[AUTO] GET /manage/plugin/pluginHeartBeat',
    group: 'plugin',
    aliases: ['plugin/pluginHeartBeat'],
  },
  {
    code: 'plugin.getPluginShopList',
    method: 'GET',
    path: '/manage/plugin/getPluginShopList',
    desc: '[AUTO] GET /manage/plugin/getPluginShopList',
    group: 'plugin',
    aliases: ['plugin/getPluginShopList'],
  },
  {
    code: 'plugin.getOneShopPlugin',
    method: 'GET',
    path: '/manage/plugin/getOneShopPlugin',
    desc: '[AUTO] GET /manage/plugin/getOneShopPlugin',
    group: 'plugin',
    aliases: ['plugin/getOneShopPlugin'],
  },
  {
    code: 'plugin.createInvoice',
    method: 'POST',
    path: '/manage/plugin/createInvoice',
    desc: '[AUTO] POST /manage/plugin/createInvoice',
    group: 'plugin',
    aliases: ['plugin/createInvoice'],
  },
  {
    code: 'plugin.checkInvoice',
    method: 'POST',
    path: '/manage/plugin/checkInvoice',
    desc: '[AUTO] POST /manage/plugin/checkInvoice',
    group: 'plugin',
    aliases: ['plugin/checkInvoice'],
  },
  {
    code: 'menu.updateOrder',
    method: 'POST',
    path: '/manage/menu/updateOrder',
    desc: '[AUTO] POST /manage/menu/updateOrder',
    group: 'menu',
    aliases: ['menu/updateOrder'],
  },
  {
    code: 'menu.batchUpdateStatus',
    method: 'POST',
    path: '/manage/menu/batchUpdateStatus',
    desc: '[AUTO] POST /manage/menu/batchUpdateStatus',
    group: 'menu',
    aliases: ['menu/batchUpdateStatus'],
  },
  {
    code: 'role.getAllList',
    method: 'GET',
    path: '/manage/role/getAllList',
    desc: '[AUTO] GET /manage/role/getAllList',
    group: 'role',
    aliases: ['role/getAllList'],
  },
  {
    code: 'admin.getUserInfo',
    method: 'GET',
    path: '/manage/admin/getUserInfo',
    desc: '[AUTO] GET /manage/admin/getUserInfo',
    group: 'admin',
    aliases: ['admin/getUserInfo'],
  },
  {
    code: 'admin.getUserRoutes',
    method: 'GET',
    path: '/manage/admin/getUserRoutes',
    desc: '[AUTO] GET /manage/admin/getUserRoutes',
    group: 'admin',
    aliases: ['admin/getUserRoutes'],
  },
  {
    code: 'admin.logOut',
    method: 'GET',
    path: '/manage/admin/logOut',
    desc: '[AUTO] GET /manage/admin/logOut',
    group: 'admin',
    aliases: ['admin/logOut'],
  },
  {
    code: 'ads.getList',
    method: 'GET',
    path: '/manage/ads/getList',
    desc: '[AUTO] GET /manage/ads/getList',
    group: 'ads',
    aliases: ['ads/getList'],
  },
  {
    code: 'ads.getOne',
    method: 'GET',
    path: '/manage/ads/getOne',
    desc: '[AUTO] GET /manage/ads/getOne',
    group: 'ads',
    aliases: ['ads/getOne'],
  },
  {
    code: 'ads.addOne',
    method: 'POST',
    path: '/manage/ads/addOne',
    desc: '[AUTO] POST /manage/ads/addOne',
    group: 'ads',
    aliases: ['ads/addOne'],
  },
  {
    code: 'ads.updateOne',
    method: 'POST',
    path: '/manage/ads/updateOne',
    desc: '[AUTO] POST /manage/ads/updateOne',
    group: 'ads',
    aliases: ['ads/updateOne'],
  },
  {
    code: 'ads.delete',
    method: 'POST',
    path: '/manage/ads/delete',
    desc: '[AUTO] POST /manage/ads/delete',
    group: 'ads',
    aliases: ['ads/delete'],
  },
  {
    code: 'content.getList',
    method: 'GET',
    path: '/manage/content/getList',
    desc: '[AUTO] GET /manage/content/getList',
    group: 'content',
    aliases: ['content/getList'],
  },
  {
    code: 'content.getContent',
    method: 'GET',
    path: '/manage/content/getContent',
    desc: '[AUTO] GET /manage/content/getContent',
    group: 'content',
    aliases: ['content/getContent'],
  },
  {
    code: 'content.addOne',
    method: 'POST',
    path: '/manage/content/addOne',
    desc: '[AUTO] POST /manage/content/addOne',
    group: 'content',
    aliases: ['content/addOne'],
  },
  {
    code: 'content.updateOne',
    method: 'POST',
    path: '/manage/content/updateOne',
    desc: '[AUTO] POST /manage/content/updateOne',
    group: 'content',
    aliases: ['content/updateOne'],
  },
  {
    code: 'content.updateContents',
    method: 'POST',
    path: '/manage/content/updateContents',
    desc: '[AUTO] POST /manage/content/updateContents',
    group: 'content',
    aliases: ['content/updateContents'],
  },
  {
    code: 'content.deleteContent',
    method: 'POST',
    path: '/manage/content/deleteContent',
    desc: '[AUTO] POST /manage/content/deleteContent',
    group: 'content',
    aliases: ['content/deleteContent'],
  },
  {
    code: 'content.topContent',
    method: 'POST',
    path: '/manage/content/topContent',
    desc: '[AUTO] POST /manage/content/topContent',
    group: 'content',
    aliases: ['content/topContent'],
  },
  {
    code: 'content.roofContent',
    method: 'POST',
    path: '/manage/content/roofContent',
    desc: '[AUTO] POST /manage/content/roofContent',
    group: 'content',
    aliases: ['content/roofContent'],
  },
  {
    code: 'content.redictContentToUsers',
    method: 'POST',
    path: '/manage/content/redictContentToUsers',
    desc: '[AUTO] POST /manage/content/redictContentToUsers',
    group: 'content',
    aliases: ['content/redictContentToUsers'],
  },
  {
    code: 'content.updateContentEditor',
    method: 'POST',
    path: '/manage/content/updateContentEditor',
    desc: '[AUTO] POST /manage/content/updateContentEditor',
    group: 'content',
    aliases: ['content/updateContentEditor'],
  },
  {
    code: 'content.moveCate',
    method: 'POST',
    path: '/manage/content/moveCate',
    desc: '[AUTO] POST /manage/content/moveCate',
    group: 'content',
    aliases: ['content/moveCate'],
  },
  {
    code: 'contentCategory.getList',
    method: 'GET',
    path: '/manage/contentCategory/getList',
    desc: '[AUTO] GET /manage/contentCategory/getList',
    group: 'contentCategory',
    aliases: ['contentCategory/getList'],
  },
  {
    code: 'contentCategory.getOne',
    method: 'GET',
    path: '/manage/contentCategory/getOne',
    desc: '[AUTO] GET /manage/contentCategory/getOne',
    group: 'contentCategory',
    aliases: ['contentCategory/getOne'],
  },
  {
    code: 'contentCategory.addOne',
    method: 'POST',
    path: '/manage/contentCategory/addOne',
    desc: '[AUTO] POST /manage/contentCategory/addOne',
    group: 'contentCategory',
    aliases: ['contentCategory/addOne'],
  },
  {
    code: 'contentCategory.updateOne',
    method: 'POST',
    path: '/manage/contentCategory/updateOne',
    desc: '[AUTO] POST /manage/contentCategory/updateOne',
    group: 'contentCategory',
    aliases: ['contentCategory/updateOne'],
  },
  {
    code: 'contentCategory.deleteCategory',
    method: 'POST',
    path: '/manage/contentCategory/deleteCategory',
    desc: '[AUTO] POST /manage/contentCategory/deleteCategory',
    group: 'contentCategory',
    aliases: ['contentCategory/deleteCategory'],
  },
  {
    code: 'contentMessage.getList',
    method: 'GET',
    path: '/manage/contentMessage/getList',
    desc: '[AUTO] GET /manage/contentMessage/getList',
    group: 'contentMessage',
    aliases: ['contentMessage/getList'],
  },
  {
    code: 'contentMessage.getOne',
    method: 'GET',
    path: '/manage/contentMessage/getOne',
    desc: '[AUTO] GET /manage/contentMessage/getOne',
    group: 'contentMessage',
    aliases: ['contentMessage/getOne'],
  },
  {
    code: 'contentMessage.addOne',
    method: 'POST',
    path: '/manage/contentMessage/addOne',
    desc: '[AUTO] POST /manage/contentMessage/addOne',
    group: 'contentMessage',
    aliases: ['contentMessage/addOne'],
  },
  {
    code: 'contentMessage.deleteMessage',
    method: 'POST',
    path: '/manage/contentMessage/deleteMessage',
    desc: '[AUTO] POST /manage/contentMessage/deleteMessage',
    group: 'contentMessage',
    aliases: ['contentMessage/deleteMessage'],
  },
  {
    code: 'contentMessage.batchUpdateState',
    method: 'POST',
    path: '/manage/contentMessage/batchUpdateState',
    desc: '[AUTO] POST /manage/contentMessage/batchUpdateState',
    group: 'contentMessage',
    aliases: ['contentMessage/batchUpdateState'],
  },
  {
    code: 'contentMessage.getStats',
    method: 'GET',
    path: '/manage/contentMessage/getStats',
    desc: '[AUTO] GET /manage/contentMessage/getStats',
    group: 'contentMessage',
    aliases: ['contentMessage/getStats'],
  },
  {
    code: 'contentMessage.auditMessage',
    method: 'POST',
    path: '/manage/contentMessage/auditMessage',
    desc: '[AUTO] POST /manage/contentMessage/auditMessage',
    group: 'contentMessage',
    aliases: ['contentMessage/auditMessage'],
  },
  {
    code: 'contentMessage.batchAuditMessages',
    method: 'POST',
    path: '/manage/contentMessage/batchAuditMessages',
    desc: '[AUTO] POST /manage/contentMessage/batchAuditMessages',
    group: 'contentMessage',
    aliases: ['contentMessage/batchAuditMessages'],
  },
  {
    code: 'contentTag.getList',
    method: 'GET',
    path: '/manage/contentTag/getList',
    desc: '[AUTO] GET /manage/contentTag/getList',
    group: 'contentTag',
    aliases: ['contentTag/getList'],
  },
  {
    code: 'contentTag.getOne',
    method: 'GET',
    path: '/manage/contentTag/getOne',
    desc: '[AUTO] GET /manage/contentTag/getOne',
    group: 'contentTag',
    aliases: ['contentTag/getOne'],
  },
  {
    code: 'contentTag.addOne',
    method: 'POST',
    path: '/manage/contentTag/addOne',
    desc: '[AUTO] POST /manage/contentTag/addOne',
    group: 'contentTag',
    aliases: ['contentTag/addOne'],
  },
  {
    code: 'contentTag.updateOne',
    method: 'POST',
    path: '/manage/contentTag/updateOne',
    desc: '[AUTO] POST /manage/contentTag/updateOne',
    group: 'contentTag',
    aliases: ['contentTag/updateOne'],
  },
  {
    code: 'contentTag.deleteTag',
    method: 'POST',
    path: '/manage/contentTag/deleteTag',
    desc: '[AUTO] POST /manage/contentTag/deleteTag',
    group: 'contentTag',
    aliases: ['contentTag/deleteTag'],
  },
  {
    code: 'mailTemplate.getList',
    method: 'GET',
    path: '/manage/mailTemplate/getList',
    desc: '[AUTO] GET /manage/mailTemplate/getList',
    group: 'mailTemplate',
    aliases: ['mailTemplate/getList'],
  },
  {
    code: 'mailTemplate.getTypeList',
    method: 'GET',
    path: '/manage/mailTemplate/getTypeList',
    desc: '[AUTO] GET /manage/mailTemplate/getTypeList',
    group: 'mailTemplate',
    aliases: ['mailTemplate/getTypeList'],
  },
  {
    code: 'mailTemplate.getOne',
    method: 'GET',
    path: '/manage/mailTemplate/getOne',
    desc: '[AUTO] GET /manage/mailTemplate/getOne',
    group: 'mailTemplate',
    aliases: ['mailTemplate/getOne'],
  },
  {
    code: 'mailTemplate.addOne',
    method: 'POST',
    path: '/manage/mailTemplate/addOne',
    desc: '[AUTO] POST /manage/mailTemplate/addOne',
    group: 'mailTemplate',
    aliases: ['mailTemplate/addOne'],
  },
  {
    code: 'mailTemplate.updateOne',
    method: 'POST',
    path: '/manage/mailTemplate/updateOne',
    desc: '[AUTO] POST /manage/mailTemplate/updateOne',
    group: 'mailTemplate',
    aliases: ['mailTemplate/updateOne'],
  },
  {
    code: 'mailTemplate.delete',
    method: 'POST',
    path: '/manage/mailTemplate/delete',
    desc: '[AUTO] POST /manage/mailTemplate/delete',
    group: 'mailTemplate',
    aliases: ['mailTemplate/delete'],
  },
  {
    code: 'regUser.getList',
    method: 'GET',
    path: '/manage/regUser/getList',
    desc: '[AUTO] GET /manage/regUser/getList',
    group: 'regUser',
    aliases: ['regUser/getList'],
  },
  {
    code: 'regUser.getOne',
    method: 'GET',
    path: '/manage/regUser/getOne',
    desc: '[AUTO] GET /manage/regUser/getOne',
    group: 'regUser',
    aliases: ['regUser/getOne'],
  },
  {
    code: 'regUser.updateOne',
    method: 'POST',
    path: '/manage/regUser/updateOne',
    desc: '[AUTO] POST /manage/regUser/updateOne',
    group: 'regUser',
    aliases: ['regUser/updateOne'],
  },
  {
    code: 'regUser.deleteUser',
    method: 'POST',
    path: '/manage/regUser/deleteUser',
    desc: '[AUTO] POST /manage/regUser/deleteUser',
    group: 'regUser',
    aliases: ['regUser/deleteUser'],
  },
  {
    code: 'systemOptionLog.getList',
    method: 'GET',
    path: '/manage/systemOptionLog/getList',
    desc: '[AUTO] GET /manage/systemOptionLog/getList',
    group: 'systemOptionLog',
    aliases: ['systemOptionLog/getList'],
  },
  {
    code: 'systemOptionLog.deleteLogItem',
    method: 'POST',
    path: '/manage/systemOptionLog/deleteLogItem',
    desc: '[AUTO] POST /manage/systemOptionLog/deleteLogItem',
    group: 'systemOptionLog',
    aliases: ['systemOptionLog/deleteLogItem'],
  },
  {
    code: 'systemOptionLog.deleteAllLogItem',
    method: 'POST',
    path: '/manage/systemOptionLog/deleteAllLogItem',
    desc: '[AUTO] POST /manage/systemOptionLog/deleteAllLogItem',
    group: 'systemOptionLog',
    aliases: ['systemOptionLog/deleteAllLogItem'],
  },
  {
    code: 'uploadFile.getList',
    method: 'GET',
    path: '/manage/uploadFile/getList',
    desc: '[AUTO] GET /manage/uploadFile/getList',
    group: 'uploadFile',
    aliases: ['uploadFile/getList'],
  },
  {
    code: 'uploadFile.updateOne',
    method: 'POST',
    path: '/manage/uploadFile/updateOne',
    desc: '[AUTO] POST /manage/uploadFile/updateOne',
    group: 'uploadFile',
    aliases: ['uploadFile/updateOne'],
  },
  {
    code: 'uploadFile.delete',
    method: 'POST',
    path: '/manage/uploadFile/delete',
    desc: '[AUTO] POST /manage/uploadFile/delete',
    group: 'uploadFile',
    aliases: ['uploadFile/delete'],
  },
  {
    code: 'cache.stats',
    method: 'GET',
    path: '/manage/cache/stats',
    desc: '[AUTO] GET /manage/cache/stats',
    group: 'cache',
    aliases: ['cache/stats'],
  },
  {
    code: 'cache.config',
    method: 'GET',
    path: '/manage/cache/config',
    desc: '[AUTO] GET /manage/cache/config',
    group: 'cache',
    aliases: ['cache/config'],
  },
  {
    code: 'cache.hotspots',
    method: 'GET',
    path: '/manage/cache/hotspots',
    desc: '[AUTO] GET /manage/cache/hotspots',
    group: 'cache',
    aliases: ['cache/hotspots'],
  },
  {
    code: 'cache.warmup',
    method: 'POST',
    path: '/manage/cache/warmup',
    desc: '[AUTO] POST /manage/cache/warmup',
    group: 'cache',
    aliases: ['cache/warmup'],
  },
  {
    code: 'cache.clear',
    method: 'POST',
    path: '/manage/cache/clear',
    desc: '[AUTO] POST /manage/cache/clear',
    group: 'cache',
    aliases: ['cache/clear'],
  },
  {
    code: 'cache.resetStats',
    method: 'POST',
    path: '/manage/cache/resetStats',
    desc: '[AUTO] POST /manage/cache/resetStats',
    group: 'cache',
    aliases: ['cache/resetStats'],
  },
  {
    code: 'sitemap.status',
    method: 'GET',
    path: '/manage/sitemap/status',
    desc: '[AUTO] GET /manage/sitemap/status',
    group: 'sitemap',
    aliases: ['sitemap/status'],
  },
  {
    code: 'sitemap.refresh',
    method: 'POST',
    path: '/manage/sitemap/refresh',
    desc: '[AUTO] POST /manage/sitemap/refresh',
    group: 'sitemap',
    aliases: ['sitemap/refresh'],
  },
  {
    code: 'sitemap.clearCache',
    method: 'POST',
    path: '/manage/sitemap/clearCache',
    desc: '[AUTO] POST /manage/sitemap/clearCache',
    group: 'sitemap',
    aliases: ['sitemap/clearCache'],
  },
  {
    code: 'sitemap.preview',
    method: 'GET',
    path: '/manage/sitemap/preview',
    desc: '[AUTO] GET /manage/sitemap/preview',
    group: 'sitemap',
    aliases: ['sitemap/preview'],
  },
  {
    code: 'sitemap.config',
    method: 'GET',
    path: '/manage/sitemap/config',
    desc: '[AUTO] GET /manage/sitemap/config',
    group: 'sitemap',
    aliases: ['sitemap/config'],
  },
  {
    code: 'sitemap.config',
    method: 'POST',
    path: '/manage/sitemap/config',
    desc: '[AUTO] POST /manage/sitemap/config',
    group: 'sitemap',
    aliases: ['sitemap/config'],
  },
  {
    code: 'sitemap.test',
    method: 'GET',
    path: '/manage/sitemap/test',
    desc: '[AUTO] GET /manage/sitemap/test',
    group: 'sitemap',
    aliases: ['sitemap/test'],
  },
];
