'use strict';

/**
 * ⚠️ 此文件由 scripts/generate-permissions.js 自动生成
 * 更新时间: 2026-01-25T00:44:17.203Z
 */

module.exports = [
  {
    code: 'admins.login',
    method: 'POST',
    path: '/manage/v1/admins/login',
    desc: '管理员登录',
    group: 'admins',
    aliases: ['admins/login'],
  },
  {
    code: 'admins.status',
    method: 'GET',
    path: '/manage/v1/admins/init/status',
    desc: '获取初始化状态',
    group: 'admins',
    aliases: ['admins/status'],
  },
  {
    code: 'admins.init',
    method: 'POST',
    path: '/manage/v1/admins/init',
    desc: '初始化超级管理员',
    group: 'admins',
    aliases: ['admins/init'],
  },
  {
    code: 'admins.me',
    method: 'GET',
    path: '/manage/v1/admins/me',
    desc: '获取当前管理员信息',
    group: 'admins',
    aliases: ['admins/me'],
  },
  {
    code: 'admins.routes',
    method: 'GET',
    path: '/manage/v1/admins/me/routes',
    desc: '获取管理员路由权限',
    group: 'admins',
    aliases: ['admins/routes'],
  },
  {
    code: 'admins.logout',
    method: 'POST',
    path: '/manage/v1/admins/logout',
    desc: '管理员登出',
    group: 'admins',
    aliases: ['admins/logout'],
  },
  {
    code: 'admins.list',
    method: 'GET',
    path: '/manage/v1/admins',
    desc: '获取管理员列表',
    group: 'admins',
    aliases: ['admins/list'],
  },
  {
    code: 'admins.post',
    method: 'POST',
    path: '/manage/v1/admins',
    desc: '创建管理员',
    group: 'admins',
    aliases: ['admins/post'],
  },
  {
    code: 'admins.put',
    method: 'PUT',
    path: '/manage/v1/admins/:id',
    desc: '更新管理员信息',
    group: 'admins',
    aliases: ['admins/put'],
  },
  {
    code: 'admins.delete',
    method: 'DELETE',
    path: '/manage/v1/admins/:id',
    desc: '删除管理员',
    group: 'admins',
    aliases: ['admins/delete'],
  },
  {
    code: 'content.list',
    method: 'GET',
    path: '/manage/v1/content',
    desc: '获取内容列表',
    group: 'content',
    aliases: ['content/list'],
  },
  {
    code: 'content.batch',
    method: 'PUT',
    path: '/manage/v1/content/batch',
    desc: '批量更新内容',
    group: 'content',
    aliases: ['content/batch'],
  },
  {
    code: 'content.detail',
    method: 'GET',
    path: '/manage/v1/content/:id',
    desc: '获取内容详情（参数化路由，必须在特定路由之后）',
    group: 'content',
    aliases: ['content/detail'],
  },
  {
    code: 'content.post',
    method: 'POST',
    path: '/manage/v1/content',
    desc: '创建内容',
    group: 'content',
    aliases: ['content/post'],
  },
  {
    code: 'content.put',
    method: 'PUT',
    path: '/manage/v1/content/:id',
    desc: '更新内容',
    group: 'content',
    aliases: ['content/put'],
  },
  {
    code: 'content.delete',
    method: 'DELETE',
    path: '/manage/v1/content/:id',
    desc: '删除内容',
    group: 'content',
    aliases: ['content/delete'],
  },
  {
    code: 'content.top',
    method: 'PUT',
    path: '/manage/v1/content/:id/top',
    desc: '置顶内容',
    group: 'content',
    aliases: ['content/top'],
  },
  {
    code: 'content.pin',
    method: 'PUT',
    path: '/manage/v1/content/:id/pin',
    desc: '固定内容',
    group: 'content',
    aliases: ['content/pin'],
  },
  {
    code: 'content.assignments',
    method: 'POST',
    path: '/manage/v1/content/:id/assignments',
    desc: '分配内容给用户',
    group: 'content',
    aliases: ['content/assignments'],
  },
  {
    code: 'content.editor',
    method: 'PUT',
    path: '/manage/v1/content/:id/editor',
    desc: '更新内容编辑器',
    group: 'content',
    aliases: ['content/editor'],
  },
  {
    code: 'content.category',
    method: 'PUT',
    path: '/manage/v1/content/:id/category',
    desc: '移动内容分类',
    group: 'content',
    aliases: ['content/category'],
  },
  {
    code: 'ads.list',
    method: 'GET',
    path: '/manage/v1/ads',
    desc: '获取广告列表',
    group: 'ads',
    aliases: ['ads/list'],
  },
  {
    code: 'ads.detail',
    method: 'GET',
    path: '/manage/v1/ads/:id',
    desc: '获取广告详情',
    group: 'ads',
    aliases: ['ads/detail'],
  },
  {
    code: 'ads.post',
    method: 'POST',
    path: '/manage/v1/ads',
    desc: '创建广告',
    group: 'ads',
    aliases: ['ads/post'],
  },
  {
    code: 'ads.put',
    method: 'PUT',
    path: '/manage/v1/ads/:id',
    desc: '更新广告',
    group: 'ads',
    aliases: ['ads/put'],
  },
  {
    code: 'ads.delete',
    method: 'DELETE',
    path: '/manage/v1/ads/:id',
    desc: '删除广告',
    group: 'ads',
    aliases: ['ads/delete'],
  },
  {
    code: 'categories.list',
    method: 'GET',
    path: '/manage/v1/categories',
    desc: '获取分类列表',
    group: 'categories',
    aliases: ['categories/list'],
  },
  {
    code: 'categories.detail',
    method: 'GET',
    path: '/manage/v1/categories/:id',
    desc: '获取分类详情',
    group: 'categories',
    aliases: ['categories/detail'],
  },
  {
    code: 'categories.post',
    method: 'POST',
    path: '/manage/v1/categories',
    desc: '创建分类',
    group: 'categories',
    aliases: ['categories/post'],
  },
  {
    code: 'categories.put',
    method: 'PUT',
    path: '/manage/v1/categories/:id',
    desc: '更新分类',
    group: 'categories',
    aliases: ['categories/put'],
  },
  {
    code: 'categories.delete',
    method: 'DELETE',
    path: '/manage/v1/categories/:id',
    desc: '删除分类',
    group: 'categories',
    aliases: ['categories/delete'],
  },
  {
    code: 'tags.list',
    method: 'GET',
    path: '/manage/v1/tags',
    desc: '获取标签列表',
    group: 'tags',
    aliases: ['tags/list'],
  },
  {
    code: 'tags.detail',
    method: 'GET',
    path: '/manage/v1/tags/:id',
    desc: '获取标签详情',
    group: 'tags',
    aliases: ['tags/detail'],
  },
  {
    code: 'tags.post',
    method: 'POST',
    path: '/manage/v1/tags',
    desc: '创建标签',
    group: 'tags',
    aliases: ['tags/post'],
  },
  {
    code: 'tags.put',
    method: 'PUT',
    path: '/manage/v1/tags/:id',
    desc: '更新标签',
    group: 'tags',
    aliases: ['tags/put'],
  },
  {
    code: 'tags.delete',
    method: 'DELETE',
    path: '/manage/v1/tags/:id',
    desc: '删除标签',
    group: 'tags',
    aliases: ['tags/delete'],
  },
  {
    code: 'messages.list',
    method: 'GET',
    path: '/manage/v1/messages',
    desc: '获取留言列表',
    group: 'messages',
    aliases: ['messages/list'],
  },
  {
    code: 'messages.stats',
    method: 'GET',
    path: '/manage/v1/messages/stats',
    desc: '获取留言统计',
    group: 'messages',
    aliases: ['messages/stats'],
  },
  {
    code: 'messages.state',
    method: 'PUT',
    path: '/manage/v1/messages/batch/state',
    desc: '批量更新留言状态',
    group: 'messages',
    aliases: ['messages/state'],
  },
  {
    code: 'messages.audit',
    method: 'PUT',
    path: '/manage/v1/messages/batch/audit',
    desc: '批量审核留言',
    group: 'messages',
    aliases: ['messages/audit'],
  },
  {
    code: 'messages.detail',
    method: 'GET',
    path: '/manage/v1/messages/:id',
    desc: '获取留言详情（参数化路由，必须在特定路由之后）',
    group: 'messages',
    aliases: ['messages/detail'],
  },
  {
    code: 'messages.post',
    method: 'POST',
    path: '/manage/v1/messages',
    desc: '创建留言',
    group: 'messages',
    aliases: ['messages/post'],
  },
  {
    code: 'messages.delete',
    method: 'DELETE',
    path: '/manage/v1/messages/:id',
    desc: '删除留言',
    group: 'messages',
    aliases: ['messages/delete'],
  },
  {
    code: 'messages.auditPut',
    method: 'PUT',
    path: '/manage/v1/messages/:id/audit',
    desc: '审核留言',
    group: 'messages',
    aliases: ['messages/audit-put'],
  },
  {
    code: 'users.list',
    method: 'GET',
    path: '/manage/v1/users',
    desc: '获取用户列表',
    group: 'users',
    aliases: ['users/list'],
  },
  {
    code: 'users.detail',
    method: 'GET',
    path: '/manage/v1/users/:id',
    desc: '获取用户详情',
    group: 'users',
    aliases: ['users/detail'],
  },
  {
    code: 'users.put',
    method: 'PUT',
    path: '/manage/v1/users/:id',
    desc: '更新用户信息',
    group: 'users',
    aliases: ['users/put'],
  },
  {
    code: 'users.delete',
    method: 'DELETE',
    path: '/manage/v1/users/:id',
    desc: '删除用户',
    group: 'users',
    aliases: ['users/delete'],
  },
  {
    code: 'menus.list',
    method: 'GET',
    path: '/manage/v1/menus',
    desc: '获取菜单列表',
    group: 'menus',
    aliases: ['menus/list'],
  },
  {
    code: 'menus.reorder',
    method: 'PUT',
    path: '/manage/v1/menus/reorder',
    desc: '重新排序菜单',
    group: 'menus',
    aliases: ['menus/reorder'],
  },
  {
    code: 'menus.status',
    method: 'PUT',
    path: '/manage/v1/menus/batch/status',
    desc: '批量更新菜单状态',
    group: 'menus',
    aliases: ['menus/status'],
  },
  {
    code: 'menus.post',
    method: 'POST',
    path: '/manage/v1/menus',
    desc: '创建菜单',
    group: 'menus',
    aliases: ['menus/post'],
  },
  {
    code: 'menus.put',
    method: 'PUT',
    path: '/manage/v1/menus/:id',
    desc: '更新菜单（参数化路由，必须在特定路由之后）',
    group: 'menus',
    aliases: ['menus/put'],
  },
  {
    code: 'menus.delete',
    method: 'DELETE',
    path: '/manage/v1/menus/:id',
    desc: '删除菜单',
    group: 'menus',
    aliases: ['menus/delete'],
  },
  {
    code: 'roles.list',
    method: 'GET',
    path: '/manage/v1/roles',
    desc: '获取角色列表',
    group: 'roles',
    aliases: ['roles/list'],
  },
  {
    code: 'roles.all',
    method: 'GET',
    path: '/manage/v1/roles/all',
    desc: '获取所有角色',
    group: 'roles',
    aliases: ['roles/all'],
  },
  {
    code: 'roles.post',
    method: 'POST',
    path: '/manage/v1/roles',
    desc: '创建角色',
    group: 'roles',
    aliases: ['roles/post'],
  },
  {
    code: 'roles.put',
    method: 'PUT',
    path: '/manage/v1/roles/:id',
    desc: '更新角色',
    group: 'roles',
    aliases: ['roles/put'],
  },
  {
    code: 'roles.delete',
    method: 'DELETE',
    path: '/manage/v1/roles/:id',
    desc: '删除角色',
    group: 'roles',
    aliases: ['roles/delete'],
  },
  {
    code: 'system.config',
    method: 'GET',
    path: '/manage/v1/system/config',
    desc: '获取系统配置列表',
    group: 'system',
    aliases: ['system/config'],
  },
  {
    code: 'system.configPut',
    method: 'PUT',
    path: '/manage/v1/system/config',
    desc: '更新系统配置',
    group: 'system',
    aliases: ['system/config-put'],
  },
  {
    code: 'system.configDelete',
    method: 'DELETE',
    path: '/manage/v1/system/config/:id',
    desc: '删除系统配置',
    group: 'system',
    aliases: ['system/config-delete'],
  },
  {
    code: 'mailTemplates.list',
    method: 'GET',
    path: '/manage/v1/mail-templates',
    desc: '获取邮件模板列表',
    group: 'mailTemplates',
    aliases: ['mail-templates/list'],
  },
  {
    code: 'mailTemplates.types',
    method: 'GET',
    path: '/manage/v1/mail-templates/types',
    desc: '获取邮件模板类型列表',
    group: 'mailTemplates',
    aliases: ['mail-templates/types'],
  },
  {
    code: 'mailTemplates.detail',
    method: 'GET',
    path: '/manage/v1/mail-templates/:id',
    desc: '获取邮件模板详情',
    group: 'mailTemplates',
    aliases: ['mail-templates/detail'],
  },
  {
    code: 'mailTemplates.post',
    method: 'POST',
    path: '/manage/v1/mail-templates',
    desc: '创建邮件模板',
    group: 'mailTemplates',
    aliases: ['mail-templates/post'],
  },
  {
    code: 'mailTemplates.put',
    method: 'PUT',
    path: '/manage/v1/mail-templates/:id',
    desc: '更新邮件模板',
    group: 'mailTemplates',
    aliases: ['mail-templates/put'],
  },
  {
    code: 'mailTemplates.delete',
    method: 'DELETE',
    path: '/manage/v1/mail-templates/:id',
    desc: '删除邮件模板',
    group: 'mailTemplates',
    aliases: ['mail-templates/delete'],
  },
  {
    code: 'templates.list',
    method: 'GET',
    path: '/manage/v1/templates',
    desc: '获取模板列表',
    group: 'templates',
    aliases: ['templates/list'],
  },
  {
    code: 'templates.active',
    method: 'GET',
    path: '/manage/v1/templates/active',
    desc: '获取当前激活的主题',
    group: 'templates',
    aliases: ['templates/active'],
  },
  {
    code: 'templates.stats',
    method: 'GET',
    path: '/manage/v1/templates/stats',
    desc: '获取模板统计信息',
    group: 'templates',
    aliases: ['templates/stats'],
  },
  {
    code: 'templates.market',
    method: 'GET',
    path: '/manage/v1/templates/market',
    desc: '从市场获取模板列表',
    group: 'templates',
    aliases: ['templates/market'],
  },
  {
    code: 'templates.remote',
    method: 'POST',
    path: '/manage/v1/templates/install/remote',
    desc: '从远程安装模板',
    group: 'templates',
    aliases: ['templates/remote'],
  },
  {
    code: 'templates.install',
    method: 'POST',
    path: '/manage/v1/templates/install',
    desc: '安装模板',
    group: 'templates',
    aliases: ['templates/install'],
  },
  {
    code: 'templates.batch',
    method: 'DELETE',
    path: '/manage/v1/templates/batch',
    desc: '批量删除模板',
    group: 'templates',
    aliases: ['templates/batch'],
  },
  {
    code: 'templates.status',
    method: 'PUT',
    path: '/manage/v1/templates/batch/status',
    desc: '批量更新模板状态',
    group: 'templates',
    aliases: ['templates/status'],
  },
  {
    code: 'templates.detail',
    method: 'GET',
    path: '/manage/v1/templates/:id',
    desc: '获取模板详情（参数化路由，必须在特定路由之后）',
    group: 'templates',
    aliases: ['templates/detail'],
  },
  {
    code: 'templates.post',
    method: 'POST',
    path: '/manage/v1/templates',
    desc: '创建模板',
    group: 'templates',
    aliases: ['templates/post'],
  },
  {
    code: 'templates.put',
    method: 'PUT',
    path: '/manage/v1/templates/:id',
    desc: '更新模板',
    group: 'templates',
    aliases: ['templates/put'],
  },
  {
    code: 'templates.delete',
    method: 'DELETE',
    path: '/manage/v1/templates/:id',
    desc: '删除模板',
    group: 'templates',
    aliases: ['templates/delete'],
  },
  {
    code: 'templates.activate',
    method: 'PUT',
    path: '/manage/v1/templates/:id/activate',
    desc: '激活模板',
    group: 'templates',
    aliases: ['templates/activate'],
  },
  {
    code: 'templates.deactivate',
    method: 'PUT',
    path: '/manage/v1/templates/:id/deactivate',
    desc: '停用模板',
    group: 'templates',
    aliases: ['templates/deactivate'],
  },
  {
    code: 'templates.installDelete',
    method: 'DELETE',
    path: '/manage/v1/templates/:id/install',
    desc: '卸载模板',
    group: 'templates',
    aliases: ['templates/install-delete'],
  },
  {
    code: 'templates.export',
    method: 'GET',
    path: '/manage/v1/templates/:id/export',
    desc: '导出模板',
    group: 'templates',
    aliases: ['templates/export'],
  },
  {
    code: 'templates.check',
    method: 'GET',
    path: '/manage/v1/templates/:id/check',
    desc: '检查模板完整性',
    group: 'templates',
    aliases: ['templates/check'],
  },
  {
    code: 'templates.files',
    method: 'GET',
    path: '/manage/v1/templates/:id/files',
    desc: '获取模板文件列表',
    group: 'templates',
    aliases: ['templates/files'],
  },
  {
    code: 'templates.statsPut',
    method: 'PUT',
    path: '/manage/v1/templates/:id/stats',
    desc: '更新模板统计',
    group: 'templates',
    aliases: ['templates/stats-put'],
  },
  {
    code: 'templates.preview',
    method: 'GET',
    path: '/manage/v1/templates/:id/preview',
    desc: '预览模板',
    group: 'templates',
    aliases: ['templates/preview'],
  },
  {
    code: 'plugins.list',
    method: 'GET',
    path: '/manage/v1/plugins',
    desc: '获取插件列表',
    group: 'plugins',
    aliases: ['plugins/list'],
  },
  {
    code: 'plugins.install',
    method: 'POST',
    path: '/manage/v1/plugins/install',
    desc: '安装插件',
    group: 'plugins',
    aliases: ['plugins/install'],
  },
  {
    code: 'plugins.heartbeat',
    method: 'GET',
    path: '/manage/v1/plugins/heartbeat',
    desc: '插件心跳检测',
    group: 'plugins',
    aliases: ['plugins/heartbeat'],
  },
  {
    code: 'plugins.market',
    method: 'GET',
    path: '/manage/v1/plugins/market',
    desc: '获取插件市场列表',
    group: 'plugins',
    aliases: ['plugins/market'],
  },
  {
    code: 'plugins.invoices',
    method: 'POST',
    path: '/manage/v1/plugins/invoices',
    desc: '创建插件发票',
    group: 'plugins',
    aliases: ['plugins/invoices'],
  },
  {
    code: 'plugins.check',
    method: 'POST',
    path: '/manage/v1/plugins/invoices/check',
    desc: '检查插件发票',
    group: 'plugins',
    aliases: ['plugins/check'],
  },
  {
    code: 'plugins.delete',
    method: 'DELETE',
    path: '/manage/v1/plugins/:id',
    desc: '卸载插件（参数化路由，必须在特定路由之后）',
    group: 'plugins',
    aliases: ['plugins/delete'],
  },
  {
    code: 'plugins.update',
    method: 'PUT',
    path: '/manage/v1/plugins/:id/update',
    desc: '更新插件',
    group: 'plugins',
    aliases: ['plugins/update'],
  },
  {
    code: 'plugins.enable',
    method: 'PUT',
    path: '/manage/v1/plugins/:id/enable',
    desc: '启用插件',
    group: 'plugins',
    aliases: ['plugins/enable'],
  },
  {
    code: 'plugins.marketGet',
    method: 'GET',
    path: '/manage/v1/plugins/market/:id',
    desc: '获取插件市场详情',
    group: 'plugins',
    aliases: ['plugins/market-get'],
  },
  {
    code: 'logs.list',
    method: 'GET',
    path: '/manage/v1/logs',
    desc: '获取日志列表',
    group: 'logs',
    aliases: ['logs/list'],
  },
  {
    code: 'logs.all',
    method: 'DELETE',
    path: '/manage/v1/logs/all',
    desc: '清空所有日志',
    group: 'logs',
    aliases: ['logs/all'],
  },
  {
    code: 'logs.delete',
    method: 'DELETE',
    path: '/manage/v1/logs/:id',
    desc: '删除日志（参数化路由，必须在特定路由之后）',
    group: 'logs',
    aliases: ['logs/delete'],
  },
  {
    code: 'files.post',
    method: 'POST',
    path: '/manage/v1/files',
    desc: '上传文件',
    group: 'files',
    aliases: ['files/post'],
  },
  {
    code: 'files.list',
    method: 'GET',
    path: '/manage/v1/files',
    desc: '获取文件列表',
    group: 'files',
    aliases: ['files/list'],
  },
  {
    code: 'files.put',
    method: 'PUT',
    path: '/manage/v1/files/:id',
    desc: '更新文件信息',
    group: 'files',
    aliases: ['files/put'],
  },
  {
    code: 'files.delete',
    method: 'DELETE',
    path: '/manage/v1/files/:id',
    desc: '删除文件',
    group: 'files',
    aliases: ['files/delete'],
  },
  {
    code: 'cache.stats',
    method: 'GET',
    path: '/manage/v1/cache/stats',
    desc: '获取缓存统计',
    group: 'cache',
    aliases: ['cache/stats'],
  },
  {
    code: 'cache.config',
    method: 'GET',
    path: '/manage/v1/cache/config',
    desc: '获取缓存配置',
    group: 'cache',
    aliases: ['cache/config'],
  },
  {
    code: 'cache.hotspots',
    method: 'GET',
    path: '/manage/v1/cache/hotspots',
    desc: '获取缓存热点',
    group: 'cache',
    aliases: ['cache/hotspots'],
  },
  {
    code: 'cache.warmup',
    method: 'POST',
    path: '/manage/v1/cache/warmup',
    desc: '预热缓存',
    group: 'cache',
    aliases: ['cache/warmup'],
  },
  {
    code: 'cache.delete',
    method: 'DELETE',
    path: '/manage/v1/cache',
    desc: '清空缓存',
    group: 'cache',
    aliases: ['cache/delete'],
  },
  {
    code: 'cache.statsDelete',
    method: 'DELETE',
    path: '/manage/v1/cache/stats',
    desc: '重置缓存统计',
    group: 'cache',
    aliases: ['cache/stats-delete'],
  },
  {
    code: 'sitemap.status',
    method: 'GET',
    path: '/manage/v1/sitemap/status',
    desc: '获取 Sitemap 状态',
    group: 'sitemap',
    aliases: ['sitemap/status'],
  },
  {
    code: 'sitemap.refresh',
    method: 'POST',
    path: '/manage/v1/sitemap/refresh',
    desc: '刷新 Sitemap',
    group: 'sitemap',
    aliases: ['sitemap/refresh'],
  },
  {
    code: 'sitemap.cache',
    method: 'DELETE',
    path: '/manage/v1/sitemap/cache',
    desc: '清空 Sitemap 缓存',
    group: 'sitemap',
    aliases: ['sitemap/cache'],
  },
  {
    code: 'sitemap.preview',
    method: 'GET',
    path: '/manage/v1/sitemap/preview',
    desc: '预览 Sitemap',
    group: 'sitemap',
    aliases: ['sitemap/preview'],
  },
  {
    code: 'sitemap.config',
    method: 'GET',
    path: '/manage/v1/sitemap/config',
    desc: '获取 Sitemap 配置',
    group: 'sitemap',
    aliases: ['sitemap/config'],
  },
  {
    code: 'sitemap.configPut',
    method: 'PUT',
    path: '/manage/v1/sitemap/config',
    desc: '更新 Sitemap 配置',
    group: 'sitemap',
    aliases: ['sitemap/config-put'],
  },
  {
    code: 'sitemap.test',
    method: 'GET',
    path: '/manage/v1/sitemap/test',
    desc: '测试 Sitemap 访问',
    group: 'sitemap',
    aliases: ['sitemap/test'],
  },
  {
    code: 'webhooks.list',
    method: 'GET',
    path: '/manage/v1/webhooks',
    desc: '获取 Webhook 列表',
    group: 'webhooks',
    aliases: ['webhooks/list'],
  },
  {
    code: 'webhooks.stats',
    method: 'GET',
    path: '/manage/v1/webhooks/stats',
    desc: '获取用户的 Webhook 统计信息',
    group: 'webhooks',
    aliases: ['webhooks/stats'],
  },
  {
    code: 'webhooks.events',
    method: 'GET',
    path: '/manage/v1/webhooks/events',
    desc: '获取所有支持的事件列表',
    group: 'webhooks',
    aliases: ['webhooks/events'],
  },
  {
    code: 'webhooks.status',
    method: 'PUT',
    path: '/manage/v1/webhooks/batch/status',
    desc: '批量更新 Webhook 状态',
    group: 'webhooks',
    aliases: ['webhooks/status'],
  },
  {
    code: 'webhooks.detail',
    method: 'GET',
    path: '/manage/v1/webhooks/:id',
    desc: '获取 Webhook 详情（参数化路由，必须在特定路由之后）',
    group: 'webhooks',
    aliases: ['webhooks/detail'],
  },
  {
    code: 'webhooks.post',
    method: 'POST',
    path: '/manage/v1/webhooks',
    desc: '创建 Webhook',
    group: 'webhooks',
    aliases: ['webhooks/post'],
  },
  {
    code: 'webhooks.put',
    method: 'PUT',
    path: '/manage/v1/webhooks/:id',
    desc: '更新 Webhook',
    group: 'webhooks',
    aliases: ['webhooks/put'],
  },
  {
    code: 'webhooks.delete',
    method: 'DELETE',
    path: '/manage/v1/webhooks/:id',
    desc: '删除 Webhook',
    group: 'webhooks',
    aliases: ['webhooks/delete'],
  },
  {
    code: 'webhooks.enable',
    method: 'PUT',
    path: '/manage/v1/webhooks/:id/enable',
    desc: '启用 Webhook',
    group: 'webhooks',
    aliases: ['webhooks/enable'],
  },
  {
    code: 'webhooks.disable',
    method: 'PUT',
    path: '/manage/v1/webhooks/:id/disable',
    desc: '禁用 Webhook',
    group: 'webhooks',
    aliases: ['webhooks/disable'],
  },
  {
    code: 'webhooks.regenerateSecret',
    method: 'POST',
    path: '/manage/v1/webhooks/:id/regenerate-secret',
    desc: '重新生成 Webhook Secret',
    group: 'webhooks',
    aliases: ['webhooks/regenerate-secret'],
  },
  {
    code: 'webhooks.statsGet',
    method: 'GET',
    path: '/manage/v1/webhooks/:id/stats',
    desc: '获取 Webhook 统计信息',
    group: 'webhooks',
    aliases: ['webhooks/stats-get'],
  },
  {
    code: 'webhooks.logs',
    method: 'GET',
    path: '/manage/v1/webhooks/:id/logs',
    desc: '获取 Webhook 日志列表',
    group: 'webhooks',
    aliases: ['webhooks/logs'],
  },
  {
    code: 'webhooks.logsGet',
    method: 'GET',
    path: '/manage/v1/webhooks/:id/logs/:logId',
    desc: '获取 Webhook 日志详情',
    group: 'webhooks',
    aliases: ['webhooks/logs-get'],
  },
  {
    code: 'webhooks.retry',
    method: 'POST',
    path: '/manage/v1/webhooks/:id/logs/:logId/retry',
    desc: '手动重试失败的 Webhook',
    group: 'webhooks',
    aliases: ['webhooks/retry'],
  },
  {
    code: 'ai.models',
    method: 'GET',
    path: '/manage/v1/ai/models',
    desc: '[AUTO] GET /manage/v1/ai/models',
    group: 'ai',
    aliases: ['ai/models'],
  },
  {
    code: 'ai.modelsGet',
    method: 'GET',
    path: '/manage/v1/ai/models/:id',
    desc: '[AUTO] GET /manage/v1/ai/models/:id',
    group: 'ai',
    aliases: ['ai/models-get'],
  },
  {
    code: 'ai.modelsPost',
    method: 'POST',
    path: '/manage/v1/ai/models',
    desc: '[AUTO] POST /manage/v1/ai/models',
    group: 'ai',
    aliases: ['ai/models-post'],
  },
  {
    code: 'ai.modelsPut',
    method: 'PUT',
    path: '/manage/v1/ai/models/:id',
    desc: '[AUTO] PUT /manage/v1/ai/models/:id',
    group: 'ai',
    aliases: ['ai/models-put'],
  },
  {
    code: 'ai.modelsDelete',
    method: 'DELETE',
    path: '/manage/v1/ai/models/:id',
    desc: '[AUTO] DELETE /manage/v1/ai/models/:id',
    group: 'ai',
    aliases: ['ai/models-delete'],
  },
  {
    code: 'ai.toggle',
    method: 'PUT',
    path: '/manage/v1/ai/models/:id/toggle',
    desc: '[AUTO] PUT /manage/v1/ai/models/:id/toggle',
    group: 'ai',
    aliases: ['ai/toggle'],
  },
  {
    code: 'ai.stats',
    method: 'GET',
    path: '/manage/v1/ai/models/:id/stats',
    desc: '[AUTO] GET /manage/v1/ai/models/:id/stats',
    group: 'ai',
    aliases: ['ai/stats'],
  },
  {
    code: 'ai.batch',
    method: 'DELETE',
    path: '/manage/v1/ai/models/batch',
    desc: '[AUTO] DELETE /manage/v1/ai/models/batch',
    group: 'ai',
    aliases: ['ai/batch'],
  },
  {
    code: 'ai.providers',
    method: 'GET',
    path: '/manage/v1/ai/providers',
    desc: '[AUTO] GET /manage/v1/ai/providers',
    group: 'ai',
    aliases: ['ai/providers'],
  },
  {
    code: 'ai.testApiKey',
    method: 'POST',
    path: '/manage/v1/ai/test-api-key',
    desc: '[AUTO] POST /manage/v1/ai/test-api-key',
    group: 'ai',
    aliases: ['ai/test-api-key'],
  },
  {
    code: 'ai.generateTitle',
    method: 'POST',
    path: '/manage/v1/ai/content/generate-title',
    desc: '[AUTO] POST /manage/v1/ai/content/generate-title',
    group: 'ai',
    aliases: ['ai/generate-title'],
  },
  {
    code: 'ai.generateSummary',
    method: 'POST',
    path: '/manage/v1/ai/content/generate-summary',
    desc: '[AUTO] POST /manage/v1/ai/content/generate-summary',
    group: 'ai',
    aliases: ['ai/generate-summary'],
  },
  {
    code: 'ai.extractTags',
    method: 'POST',
    path: '/manage/v1/ai/content/extract-tags',
    desc: '[AUTO] POST /manage/v1/ai/content/extract-tags',
    group: 'ai',
    aliases: ['ai/extract-tags'],
  },
  {
    code: 'ai.extractKeywords',
    method: 'POST',
    path: '/manage/v1/ai/content/extract-keywords',
    desc: '[AUTO] POST /manage/v1/ai/content/extract-keywords',
    group: 'ai',
    aliases: ['ai/extract-keywords'],
  },
  {
    code: 'ai.matchCategory',
    method: 'POST',
    path: '/manage/v1/ai/content/match-category',
    desc: '[AUTO] POST /manage/v1/ai/content/match-category',
    group: 'ai',
    aliases: ['ai/match-category'],
  },
  {
    code: 'ai.optimizeSeo',
    method: 'POST',
    path: '/manage/v1/ai/content/optimize-seo',
    desc: '[AUTO] POST /manage/v1/ai/content/optimize-seo',
    group: 'ai',
    aliases: ['ai/optimize-seo'],
  },
  {
    code: 'ai.checkQuality',
    method: 'POST',
    path: '/manage/v1/ai/content/check-quality',
    desc: '[AUTO] POST /manage/v1/ai/content/check-quality',
    group: 'ai',
    aliases: ['ai/check-quality'],
  },
  {
    code: 'ai.generateBatch',
    method: 'POST',
    path: '/manage/v1/ai/content/generate-batch',
    desc: '[AUTO] POST /manage/v1/ai/content/generate-batch',
    group: 'ai',
    aliases: ['ai/generate-batch'],
  },
  {
    code: 'ai.cache',
    method: 'DELETE',
    path: '/manage/v1/ai/content/cache',
    desc: '[AUTO] DELETE /manage/v1/ai/content/cache',
    group: 'ai',
    aliases: ['ai/cache'],
  },
  {
    code: 'ai.statsGet',
    method: 'GET',
    path: '/manage/v1/ai/content/cache/stats',
    desc: '[AUTO] GET /manage/v1/ai/content/cache/stats',
    group: 'ai',
    aliases: ['ai/stats-get'],
  },
  {
    code: 'ai.publish',
    method: 'POST',
    path: '/manage/v1/ai/content/publish',
    desc: '[AUTO] POST /manage/v1/ai/content/publish',
    group: 'ai',
    aliases: ['ai/publish'],
  },
  {
    code: 'ai.batchPublish',
    method: 'POST',
    path: '/manage/v1/ai/content/batch-publish',
    desc: '[AUTO] POST /manage/v1/ai/content/batch-publish',
    group: 'ai',
    aliases: ['ai/batch-publish'],
  },
  {
    code: 'ai.preview',
    method: 'POST',
    path: '/manage/v1/ai/content/preview',
    desc: '[AUTO] POST /manage/v1/ai/content/preview',
    group: 'ai',
    aliases: ['ai/preview'],
  },
  {
    code: 'ai.publishModes',
    method: 'GET',
    path: '/manage/v1/ai/content/publish-modes',
    desc: '[AUTO] GET /manage/v1/ai/content/publish-modes',
    group: 'ai',
    aliases: ['ai/publish-modes'],
  },
  {
    code: 'ai.enhancementOptions',
    method: 'GET',
    path: '/manage/v1/ai/content/enhancement-options',
    desc: '[AUTO] GET /manage/v1/ai/content/enhancement-options',
    group: 'ai',
    aliases: ['ai/enhancement-options'],
  },
  {
    code: 'ai.generate',
    method: 'POST',
    path: '/manage/v1/ai/image/generate',
    desc: '[AUTO] POST /manage/v1/ai/image/generate',
    group: 'ai',
    aliases: ['ai/generate'],
  },
  {
    code: 'ai.optimizePrompt',
    method: 'POST',
    path: '/manage/v1/ai/image/optimize-prompt',
    desc: '[AUTO] POST /manage/v1/ai/image/optimize-prompt',
    group: 'ai',
    aliases: ['ai/optimize-prompt'],
  },
  {
    code: 'ai.batchGenerate',
    method: 'POST',
    path: '/manage/v1/ai/image/batch-generate',
    desc: '[AUTO] POST /manage/v1/ai/image/batch-generate',
    group: 'ai',
    aliases: ['ai/batch-generate'],
  },
  {
    code: 'ai.modelsGet',
    method: 'GET',
    path: '/manage/v1/ai/image/models',
    desc: '[AUTO] GET /manage/v1/ai/image/models',
    group: 'ai',
    aliases: ['ai/models-get'],
  },
  {
    code: 'ai.sizes',
    method: 'GET',
    path: '/manage/v1/ai/image/sizes/:modelId',
    desc: '[AUTO] GET /manage/v1/ai/image/sizes/:modelId',
    group: 'ai',
    aliases: ['ai/sizes'],
  },
  {
    code: 'ai.capabilities',
    method: 'GET',
    path: '/manage/v1/ai/image/capabilities',
    desc: '[AUTO] GET /manage/v1/ai/image/capabilities',
    group: 'ai',
    aliases: ['ai/capabilities'],
  },
  {
    code: 'ai.examples',
    method: 'GET',
    path: '/manage/v1/ai/image/examples',
    desc: '[AUTO] GET /manage/v1/ai/image/examples',
    group: 'ai',
    aliases: ['ai/examples'],
  },
];
