export const ADMINGROUP_FORMSTATE = 'ADMINGROUP_FORMSTATE';
export const ADMINGROUP_ROLEFORMSTATE = 'ADMINGROUP_ROLEFORMSTATE';
export const ADMINGROUP_LIST = 'ADMINGROUP_LIST';
export const ADMINRESOURCE_FORMSTATE = 'ADMINRESOURCE_FORMSTATE';
export const ADMINRESOURCE_LIST = 'ADMINRESOURCE_LIST';