export const MYTEMPLATE_LIST = 'MYTEMPLATE_LIST';
export const TEMPLATECONFIG_FORMSTATE = 'TEMPLATECONFIG_FORMSTATE';
export const TEMPLATEITEMFORDER_LIST = 'TEMPLATEITEMFORDER_LIST';
export const DORACMSTEMPLATE_LIST = 'DORACMSTEMPLATE_LIST';