/**
 * @file app shell mutation types
 * @author dora(doramart@qq.com)
 */

export const ENABLE_PAGE_TRANSITION = 'ENABLE_PAGE_TRANSITION'
export const DISABLE_PAGE_TRANSITION = 'DISABLE_PAGE_TRANSITION'
export const SET_PAGE_SWITCHING = 'SET_PAGE_SWITCHING'
export const SET_PAGE_TRANSITION_NAME = 'SET_PAGE_TRANSITION_NAME'
export const SET_APP_HEADER = 'SET_APP_HEADER'
export const SET_APP_BOTTOM_NAV = 'SET_APP_BOTTOM_NAV'
export const ACTIVATE_APP_BOTTOM_NAV = 'ACTIVATE_APP_BOTTOM_NAV'
export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY'
export const SAVE_SCROLLTOP = 'SAVE_SCROLLTOP'
