/**
 * 模块配置定义
 */

import type { ModuleConfig } from '../types';

export const CORE_MODULES: Record<string, ModuleConfig> = {
  user: {
    name: '用户管理',
    description: '前台用户认证和管理',
    required: true,
    repositories: ['User'],
    services: ['user'],
    controllers: ['api/regUser', 'manage/user'],
    routes: ['/api/v1/users', '/manage/users'],
    dependencies: [],
    dependedBy: ['content', 'comment', 'webhook', 'apiKey'],
    // 注意: 用户注册验证和密码重置功能需要 mail 模块发送邮件
    // 如果禁用 mail 模块，核心功能仍可使用，但不会发送邮件通知
  },
  admin: {
    name: '管理员管理',
    description: '后台管理员认证和管理',
    required: true,
    repositories: ['Admin'],
    services: ['admin'],
    controllers: ['api/admin', 'manage/admin'],
    routes: ['/api/v1/admin/*', '/manage/v1/admins/*'],
    dependencies: [],
    dependedBy: ['role', 'menu'],
  },
  role: {
    name: '角色权限',
    description: '角色和权限管理',
    required: true,
    repositories: ['Role', 'PermissionDefinition'],
    services: ['role'],
    controllers: ['manage/role'],
    routes: ['/manage/roles'],
    dependencies: ['admin'],
    dependedBy: [],
  },
  menu: {
    name: '菜单管理',
    description: '导航菜单配置',
    required: true,
    repositories: ['Menu'],
    services: ['menu'],
    controllers: ['manage/menu'],
    routes: ['/manage/menus'],
    dependencies: ['admin'],
    dependedBy: [],
  },
  systemConfig: {
    name: '系统配置',
    description: '系统配置管理',
    required: true,
    repositories: ['SystemConfig', 'SystemOptionLog'],
    services: ['systemConfig', 'systemOptionLog'],
    controllers: ['api/systemConfig', 'manage/systemConfig'],
    routes: ['/api/v1/system/config', '/manage/system-config'],
    dependencies: [],
    dependedBy: [],
  },
  uploadFile: {
    name: '文件上传',
    description: '文件上传和管理',
    required: true,
    repositories: ['UploadFile'],
    services: ['uploadFile'],
    controllers: ['api/uploadFile', 'manage/uploadFile'],
    routes: ['/api/v1/files', '/manage/files'],
    dependencies: [],
    dependedBy: ['content'],
  },
  apiKey: {
    name: 'API Key',
    description: 'API Key 管理',
    required: true,
    repositories: ['ApiKey'],
    services: ['apiKey'],
    controllers: ['api/apiKey'],
    routes: ['/api/v1/user/api-keys'],
    dependencies: ['user'],
    dependedBy: [],
  },
  mail: {
    name: '邮件通知',
    description: '邮件发送和模板（用户注册验证、密码重置等）',
    required: true,
    repositories: ['MailTemplate'],
    services: ['mailTemplate'],
    controllers: ['api/mailTemplate', 'manage/mailTemplate'],
    routes: ['/api/v1/mail-templates', '/manage/mail-templates'],
    dependencies: [],
    dependedBy: [],
    // 注意: user 和 admin 模块的邮件通知功能依赖此模块
  },
};

export const BUSINESS_MODULES: Record<string, ModuleConfig> = {
  content: {
    name: '内容管理',
    description: '文章、分类、标签管理',
    required: false,
    repositories: ['Content', 'ContentCategory', 'ContentTag', 'ContentInteraction'],
    services: ['content', 'contentCategory', 'contentTag', 'contentInteraction'],
    controllers: ['api/content', 'manage/content'],
    routes: ['/api/v1/content', '/manage/content'],
    dependencies: ['user', 'uploadFile'],
    dependedBy: ['comment', 'webhook'],
    // AI 助手插件的 repositories（如果启用 AI 助手插件）
    aiRepositories: ['AIModel', 'AIUsageLog', 'PromptTemplate'],
  },
  comment: {
    name: '评论系统',
    description: '用户评论和互动',
    required: false,
    repositories: ['Message', 'MessageInteraction'],
    services: ['message', 'messageInteraction'],
    controllers: ['api/contentMessage', 'manage/message'],
    routes: ['/api/v1/messages', '/manage/messages'],
    dependencies: ['user', 'content'],
    dependedBy: [],
  },
  ads: {
    name: '广告管理',
    description: '广告位和广告内容',
    required: false,
    repositories: ['Ads', 'AdsItems'],
    services: ['ads', 'adsItem'],
    controllers: ['api/ads', 'manage/ads'],
    routes: ['/api/v1/ads', '/manage/ads'],
    dependencies: [],
    dependedBy: [],
  },
  template: {
    name: '模板管理',
    description: '主题模板管理',
    required: false,
    repositories: ['Template'],
    services: ['template', 'templateManager', 'templateResolver', 'templateService', 'templateHooks'],
    controllers: ['api/template', 'manage/template'],
    routes: ['/api/v1/template', '/manage/template'],
    dependencies: [],
    dependedBy: [],
  },
  webhook: {
    name: 'Webhook',
    description: '事件通知和集成',
    required: false,
    repositories: ['Webhook', 'WebhookLog'],
    services: ['webhook'],
    controllers: ['manage/webhook'],
    routes: ['/manage/webhooks'],
    dependencies: ['user', 'content'],
    dependedBy: [],
  },
  plugin: {
    name: '插件系统',
    description: '插件管理和扩展',
    required: false,
    repositories: ['Plugin'],
    services: ['plugin'],
    controllers: ['manage/plugin'],
    routes: ['/manage/plugins'],
    dependencies: [],
    dependedBy: [],
  },
};
