/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";
import MainLayout from "@/layouts/main-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
  main: MainLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "remote-page": () => import("@/views/_builtin/remote-page/[url].vue"),
  about: () => import("@/views/about/index.vue"),
  "document_content-category": () => import("@/views/document/content-category/index.vue"),
  "document_content-message": () => import("@/views/document/content-message/index.vue"),
  "document_content-tag": () => import("@/views/document/content-tag/index.vue"),
  document_content: () => import("@/views/document/content/index.vue"),
  "email_mail-template": () => import("@/views/email/mail-template/index.vue"),
  extend_plugin: () => import("@/views/extend/plugin/index.vue"),
  "extend_template-config": () => import("@/views/extend/template-config/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_ads: () => import("@/views/manage/ads/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_system-config": () => import("@/views/manage/system-config/index.vue"),
  "manage_system-option-log": () => import("@/views/manage/system-option-log/index.vue"),
  "manage_upload-file": () => import("@/views/manage/upload-file/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  "member_reg-user": () => import("@/views/member/reg-user/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
