/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'document',
    path: '/document',
    component: 'layout.base',
    meta: {
      title: 'document',
      i18nKey: 'route.document'
    },
    children: [
      {
        name: 'document_content',
        path: '/document/content',
        component: 'view.document_content',
        meta: {
          title: 'document_content',
          i18nKey: 'route.document_content'
        }
      },
      {
        name: 'document_content-category',
        path: '/document/content-category',
        component: 'view.document_content-category',
        meta: {
          title: 'document_content-category',
          i18nKey: 'route.document_content-category'
        }
      },
      {
        name: 'document_content-message',
        path: '/document/content-message',
        component: 'view.document_content-message',
        meta: {
          title: 'document_content-message',
          i18nKey: 'route.document_content-message'
        }
      },
      {
        name: 'document_content-tag',
        path: '/document/content-tag',
        component: 'view.document_content-tag',
        meta: {
          title: 'document_content-tag',
          i18nKey: 'route.document_content-tag'
        }
      }
    ]
  },
  {
    name: 'email',
    path: '/email',
    component: 'layout.base',
    meta: {
      title: 'email',
      i18nKey: 'route.email'
    },
    children: [
      {
        name: 'email_mail-template',
        path: '/email/mail-template',
        component: 'view.email_mail-template',
        meta: {
          title: 'email_mail-template',
          i18nKey: 'route.email_mail-template'
        }
      }
    ]
  },
  {
    name: 'extend',
    path: '/extend',
    component: 'layout.base',
    meta: {
      title: 'extend',
      i18nKey: 'route.extend',
      icon: 'mdi:extension',
      order: 4
    },
    children: [
      {
        name: 'extend_plugin',
        path: '/extend/plugin',
        component: 'view.extend_plugin',
        meta: {
          title: 'extend_plugin',
          i18nKey: 'route.extend_plugin'
        }
      },
      {
        name: 'extend_template-config',
        path: '/extend/template-config',
        component: 'view.extend_template-config',
        meta: {
          title: 'template-config',
          i18nKey: 'route.extend_template-config',
          icon: 'mdi:file-document-edit-outline'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 2,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_ads',
        path: '/manage/ads',
        component: 'view.manage_ads',
        meta: {
          title: 'manage_ads',
          i18nKey: 'route.manage_ads'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_system-config',
        path: '/manage/system-config',
        component: 'view.manage_system-config',
        meta: {
          title: 'manage_system-config',
          i18nKey: 'route.manage_system-config'
        }
      },
      {
        name: 'manage_system-option-log',
        path: '/manage/system-option-log',
        component: 'view.manage_system-option-log',
        meta: {
          title: 'manage_system-option-log',
          i18nKey: 'route.manage_system-option-log'
        }
      },
      {
        name: 'manage_upload-file',
        path: '/manage/upload-file',
        component: 'view.manage_upload-file',
        meta: {
          title: 'manage_upload-file',
          i18nKey: 'route.manage_upload-file'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'member',
    path: '/member',
    component: 'layout.base',
    meta: {
      title: 'member',
      i18nKey: 'route.member'
    },
    children: [
      {
        name: 'member_reg-user',
        path: '/member/reg-user',
        component: 'view.member_reg-user',
        meta: {
          title: 'member_reg-user',
          i18nKey: 'route.member_reg-user'
        }
      }
    ]
  },
  {
    name: 'remote-page',
    path: '/remote-page/:url',
    component: 'layout.base$view.remote-page',
    props: true,
    meta: {
      title: 'remote-page',
      i18nKey: 'route.remote-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
