module.exports = {
  addOne: {
    menuType: { type: 'string', required: true, enum: ['1', '2'] },
    menuName: { type: 'string', required: true },
    routeName: { type: 'string', required: true },
    routePath: { type: 'string', required: true },
    component: { type: 'string', required: false },
    i18nKey: { type: 'string', required: false },
    icon: { type: 'string', required: false },
    iconType: { type: 'string', required: false },
    parentId: { type: 'optionalDatabaseId', required: false },
    status: { type: 'string', required: false },
    keepAlive: { type: 'boolean', required: false },
    constant: { type: 'boolean', required: false },
    order: { type: 'number', required: false },
    href: { type: 'string', required: false, allowEmpty: true },
    hideInMenu: { type: 'boolean', required: false },
    activeMenu: { type: 'string', required: false, allowEmpty: true },
    multiTab: { type: 'boolean', required: false },
    fixedIndexInTab: { type: 'number', required: false },
    query: {
      type: 'array',
      required: false,
      itemType: 'object',
      rule: {
        key: { type: 'string', required: true },
        value: { type: 'string', required: true },
      },
    },
    buttons: {
      type: 'array',
      required: false,
      itemType: 'object',
      rule: {
        desc: { type: 'string', required: true },
        api: { type: 'string', required: false, allowEmpty: true },
        permissionCode: { type: 'string', required: true },
        httpMethod: {
          type: 'enum',
          required: false,
          values: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        },
      },
    },
  },
  updateOne: {
    id: { type: 'databaseId', required: true },
    menuType: { type: 'string', required: true, enum: ['1', '2'] },
    menuName: { type: 'string', required: true },
    routeName: { type: 'string', required: true },
    routePath: { type: 'string', required: true },
    component: { type: 'string', required: false },
    i18nKey: { type: 'string', required: false },
    icon: { type: 'string', required: false },
    iconType: { type: 'string', required: false },
    parentId: { type: 'optionalDatabaseId', required: false },
    status: { type: 'string', required: false },
    keepAlive: { type: 'boolean', required: false },
    constant: { type: 'boolean', required: false },
    order: { type: 'number', required: false },
    href: { type: 'string', required: false, allowEmpty: true },
    hideInMenu: { type: 'boolean', required: false },
    activeMenu: { type: 'string', required: false, allowEmpty: true },
    multiTab: { type: 'boolean', required: false },
    fixedIndexInTab: { type: 'number', required: false },
    query: {
      type: 'array',
      required: false,
      itemType: 'object',
      rule: {
        key: { type: 'string', required: true },
        value: { type: 'string', required: true },
      },
    },
    buttons: {
      type: 'array',
      required: false,
      itemType: 'object',
      rule: {
        desc: { type: 'string', required: true },
        api: { type: 'string', required: false, allowEmpty: true },
        permissionCode: { type: 'string', required: true },
        httpMethod: {
          type: 'enum',
          required: false,
          values: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        },
      },
    },
  },
  deleteMenu: {
    ids: { type: 'string', required: true }, // 保持字符串类型，因为可能是逗号分隔的多个ID
  },
};
