export const MAIN_SITEBASIC_INFO = 'MAIN_SITEBASIC_INFO';
export const ADMING_LOGINSTATE = 'ADMING_LOGINSTATE';
export const CLIENT_NOTICE = 'CLIENT_NOTICE';
export const SYSTEM_VERSION_INFO = 'SYSTEM_VERSION_INFO';