export const SINGLEUSER_FORMSTATE = 'SINGLEUSER_FORMSTATE';
export const SINGLEUSER_LIST = 'SINGLEUSER_LIST';
export const SINGLEUSER_INFO = 'SINGLEUSER_INFO';
export const SINGLEUSER_SET_TOKEN = 'SINGLEUSER_SET_TOKEN';
export const SINGLEUSER_SET_NAME = 'SINGLEUSER_SET_NAME';
export const SINGLEUSER_SET_AVATAR = 'SINGLEUSER_SET_AVATAR';