export const CONTENT_FORMSTATE = 'CONTENT_FORMSTATE';
export const CONTENT_LIST = 'CONTENT_LIST';
export const CONTENT_ONE = 'CONTENT_ONE';
export const DIRECTUSERFORMSTATE = 'DIRECTUSERFORMSTATE';
export const CONTENTCATEGORYS_LIST = 'CONTENTCATEGORYS_LIST';
export const CONTENTTAG_LIST = 'CONTENTTAG_LIST';
